### PR TITLE
add payload validation and brief docs for all resources + appropriate routes

### PR DESCRIPTION
**Pull request by ashleygwilliams**

### CODE REVIEW

**Comment by ashleygwilliams** [comment]
ready for review @sedge @gideonthomas  :bow:

**Comment by sedge** [comment]
@ashleygwilliams Can you update the `GET /` to list the docs route too?

**Comment by ashleygwilliams** [comment]
@sedge do you want `/` to redirect to `/docs` or just link to it, or are you just saying to doc those? should that be another PR?

**Comment by ashleygwilliams** [comment]
decided on do the root and doc stuff in another PR. merging.

**Pull request merged**
