### PR TITLE
Adding appveyor

### PR DESCRIPTION
**Pull request by patjouk**
Fixes MozillaFoundation/mofo-devops#512

I'll make sure the install part work first and then add the test section.

### CODE REVIEW

**Comment by patjouk** [comment]
I'm running into an issue with postgresql. My build on appveyor failed with this message:

```
COPY env.dist .env
        1 file(s) copied.
SET PGUSER=postgres
SET PGPASSWORD=Password12!
SET PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
createdb publish
createdb: could not connect to database template1: could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (::1) and accepting
	TCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
	Is the server running on host "localhost" (127.0.0.1) and accepting
	TCP/IP connections on port 5432?
Command exited with code 1
```

Apparently, postgresql service is never started :(
I'll take a look tomorrow.

**Comment by Pomax** [comment]
looking at http://help.appveyor.com/discussions/problems/3549-postgres-could-not-connect-to-server-connection-refused services are started after the install, so the postgresql bootstrap probably needs to be in a different run section.

**Comment by patjouk** [comment]
Thanks @Pomax: I reread the docs and found the part that says that services are started after the install section 😓 . I moved the `createdb` to `test_script` section and it's now working .
I'll try to add the tests now 🤞

**Comment by patjouk** [comment]
This PR is now ready for review :)

**Pull request merged**
