### PR TITLE
user projects and project GET routes

### LINKED ISSUE #9: Implement GET /users/:userID/projects w/ tests
This route is responsible for returning a list of the given users projects:
```js
{
  projects: [
    ...
  ]
}
```

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #9, #10

### CODE REVIEW

**Comment by gideonthomas** [comment]
can you add comments above each route to show what the response might look like?

**Comment by ashleygwilliams** [comment]
@gideonthomas i think that would make the code very hard to read. would be happy to write docs in the wiki on it tho

**Comment by gideonthomas** [comment]
+1 Any kind of documentation would do

**Comment by sedge** [comment]
Shouldn't the auto-docs cover this?

**Comment by ashleygwilliams** [comment]
@sedge yeah i'm gonna have to look further into how lout does that, i would hope it would, but it isn't so something is up

**Comment by ashleygwilliams** [comment]
would like to merge and will open other small PRs for the other routes, as well as sorting the docs

**Comment by sedge** [comment]
The code looks good, but can you hold off on merging until we can look over the response object? The wiki is a good place for that to live if we can't make lout do it for us.

**Comment by sedge** [comment]
Let's merge this sucker.

**Comment by ashleygwilliams** [comment]
squashed :cow:

**Pull request merged**
